# Generated by Django 3.0 on 2020-10-04 20:11

import account.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ref_barangay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brgyCode', models.CharField(max_length=50, unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Barangay',
                'verbose_name_plural': 'Barangays',
            },
        ),
        migrations.CreateModel(
            name='ref_region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('psgcCode', models.CharField(max_length=50, unique=True)),
                ('name', models.TextField()),
                ('regCode', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('is_owner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ref_purok',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('president', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_barangay_id', to='account.ref_barangay')),
            ],
        ),
        migrations.CreateModel(
            name='ref_province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('psgcCode', models.CharField(max_length=50, unique=True)),
                ('name', models.TextField()),
                ('provCode', models.CharField(max_length=50, unique=True)),
                ('f_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ref_region', to_field='regCode')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_region_id', to='account.ref_region')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='ref_citymun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('psgcCode', models.CharField(max_length=50, unique=True)),
                ('name', models.TextField()),
                ('citymunCode', models.CharField(max_length=50, unique=True)),
                ('f_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ref_province', to_field='provCode')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_province_id', to='account.ref_province')),
            ],
            options={
                'verbose_name': 'City/Municipality',
                'verbose_name_plural': 'Cities and Municipalities',
            },
        ),
        migrations.AddField(
            model_name='ref_barangay',
            name='citymun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_citymun_id', to='account.ref_citymun'),
        ),
        migrations.AddField(
            model_name='ref_barangay',
            name='f_citymun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ref_citymun', to_field='citymunCode'),
        ),
        migrations.CreateModel(
            name='household_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.BooleanField(choices=[(0, 'Male'), (1, 'Female')], default=0)),
                ('street', models.CharField(max_length=150)),
                ('verification_file', models.FileField(help_text='Select File', null=True, upload_to=account.models.filename_generator)),
                ('profile', models.FileField(help_text='Select File', null=True, upload_to=account.models.filename_generator)),
                ('account_is_verified', models.IntegerField(choices=[(0, 'Pending'), (1, 'Verified')], default=0)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('purok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ref_purok')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='family_members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('verification_file', models.FileField(help_text='Select documents', upload_to=account.models.filename_generator)),
                ('profile', models.FileField(help_text='Select File', null=True, upload_to=account.models.filename_generator)),
                ('gender', models.BooleanField(choices=[(0, 'Male'), (1, 'Female')], default=0)),
                ('is_confirm', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'decline')], default=0)),
                ('date_added', models.DateField(default=datetime.date.today)),
                ('household_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.household_profile')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Relationship')),
            ],
        ),
        migrations.CreateModel(
            name='building_owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.TextField()),
                ('street', models.CharField(max_length=150)),
                ('verification_file', models.FileField(help_text='Select File', upload_to=account.models.filename_generator)),
                ('profile', models.FileField(help_text='Select File', null=True, upload_to=account.models.filename_generator)),
                ('account_is_verified', models.IntegerField(choices=[(0, 'Pending'), (1, 'Verified')], default=0)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('is_confirm', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'decline')], default=0)),
                ('purok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ref_purok')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
